<a href="https://colab.research.google.com/github/LeSaUi/DLtest/blob/main/torch_dataset_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")
%cd drive/MyDrive/ColabNotebooks
!ls

Mounted at /content/drive
/content/drive/MyDrive/ColabNotebooks
condacolab_install.log	Untitled0.ipynb  Untitled2.ipynb  Untitled4.ipynb
telecom_churn.csv	Untitled1.ipynb  Untitled3.ipynb


In [ ]:
!pip install -q condacolab
import condacolab
condacolab.install()


⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:19
🔁 Restarting kernel...


In [ ]:
import condacolab
condacolab.check()
!conda --version
!which conda

✨🍰✨ Everything looks OK!
conda 22.11.1
/usr/local/bin/conda


In [ ]:
!pip install jupyter torch numpy pandas matplotlib seaborn

In [ ]:
!conda list

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self,text,labels):
    #초기 데이터 생성 방법 지정
    self.labels=labels
    self.data=text

  def __len__(self):
    #데이터의 전체 길이 return
    return len(self.labels)

  def __getitem__(self,idx):
    #index 값을 주었을 때 반환되는 데이터의 형태(x,y)
    label=self.labels[idx]
    text=self.data[idx]
    sample={"Text":text,"Class":label}
    return sample



In [ ]:
text=["Happy","Amazing","Sad","Unhappy","Glum"]
labels=["Positive","Positive","Negative","Negative","Negative"]

#Dataset 생성
MyDataset=CustomDataset(text,labels)

#DataLoader 생성(배치 크기2, 매 epoch마다 데이터셋 shuffle)
MyDataLoader=DataLoader(MyDataset,batch_size=2,shuffle=True)

for dataset in MyDataLoader:
  print(dataset)


{'Text': ['Unhappy', 'Amazing'], 'Class': ['Negative', 'Positive']}
{'Text': ['Happy', 'Sad'], 'Class': ['Positive', 'Negative']}
{'Text': ['Glum'], 'Class': ['Negative']}


In [ ]:
from torch.utils.data import Dataset, DataLoader
import torch

class ExampleDataset(Dataset):
  def __init__(self,num):
    self.num=num

  def __len__(self):
    return self.num

  def __getitem__(self,idx):
    return {"X":torch.tensor([idx]*(idx+1),dtype=torch.float32),"y":torch.tensor(idx,dtype=torch.float32)}

dataset_example=ExampleDataset(10)
dataloader_example=DataLoader(dataset_example,batch_size=1)
for d in dataloader_example:
  print("X",d["X"])

X tensor([[0.]])
X tensor([[1., 1.]])
X tensor([[2., 2., 2.]])
X tensor([[3., 3., 3., 3.]])
X tensor([[4., 4., 4., 4., 4.]])
X tensor([[5., 5., 5., 5., 5., 5.]])
X tensor([[6., 6., 6., 6., 6., 6., 6.]])
X tensor([[7., 7., 7., 7., 7., 7., 7., 7.]])
X tensor([[8., 8., 8., 8., 8., 8., 8., 8., 8.]])
X tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])


In [ ]:
dataloader_example2=DataLoader(dataset_example,batch_size=2)
for d in dataloader_example2:
  print(d["X"])

RuntimeError: ignored

In [ ]:
def my_collate_fn(samples):
  collate_X=[]
  collate_y=[]
  max_len=max(len(sample["X"])for sample in samples)

  for sample in samples:
    diff=max_len-len(sample["X"])
    if diff>0:
      zero_pad=torch.zeros(size=(diff,))
      collate_X+=[torch.cat([sample["X"],zero_pad],dim=0)]
    else:
      collate_X+=[sample["X"]]
  
  collate_y=[sample["y"]for sample in samples]

  return {"X":torch.stack(collate_X),"y":torch.stack(collate_y)}

dataloader_example=DataLoader(dataset_example,batch_size=2,collate_fn=my_collate_fn)

for d in dataloader_example:
  print(d["X"],d['y'])

tensor([[0., 0.],
        [1., 1.]]) tensor([0., 1.])
tensor([[2., 2., 2., 0.],
        [3., 3., 3., 3.]]) tensor([2., 3.])
tensor([[4., 4., 4., 4., 4., 0.],
        [5., 5., 5., 5., 5., 5.]]) tensor([4., 5.])
tensor([[6., 6., 6., 6., 6., 6., 6., 0.],
        [7., 7., 7., 7., 7., 7., 7., 7.]]) tensor([6., 7.])
tensor([[8., 8., 8., 8., 8., 8., 8., 8., 8., 0.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]]) tensor([8., 9.])


In [ ]:
a=[[1, 1], [2, 1], [2, 2], [1, 2],[3,1],[1,4],[5,-1],[-1,10]]

print(max(a),max(a)[0])

print(min(a),min(a)[1])


[5, -1] 5
[-1, 10] 10
